import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers";
import Appbar from "./components/Appbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
        {/* <header className="p-4 bg-blue-400">
          <p>Header</p>
        </header> */}
        <Providers>
          <Appbar/>
        {children}
        </Providers>
        {/* <footer className="p-16 bg-blue-300">
          <p>Footer</p>
        </footer> */}
      </body>
    </html>
  );
}
